var fs = require("fs"); // Import Module

// URL Encoded Characters
var codes = 
[
	"%08", 
	"%09", 
	"%0A", 
	"%0D", 
	"%20", 
	"%21", 
	"%22", 
	"%23", 
	"%24", 
	"%25", 
	"%26", 
	"%27", 
	"%28", 
	"%29", 
	"%2A", 
	"%2B", 
	"%2C", 
	"%2D", 
	"%2E", 
	"%2F",
	"%30",
	"%31",
	"%32",
	"%33",
	"%34",
	"%35",
	"%36",
	"%37",
	"%38",
	"%39",
	"%3A",
	"%3B",
	"%3C",
	"%3D",
	"%3E",
	"%3F",
	"%40",
	"%41",
	"%42",
	"%43",
	"%44",
	"%45",
	"%46",
	"%47",
	"%48",
	"%49",
	"%4A",
	"%4B",
	"%4C",
	"%4D",
	"%4E",
	"%4F",
	"%50",
	"%51",
	"%52",
	"%53",
	"%54",
	"%55",
	"%56",
	"%57",
	"%58",
	"%59",
	"%5A",
	"%5B",
	"%5C",
	"%5D",
	"%5E",
	"%5F",
	"%60",
	"%61",
	"%62",
	"%63",
	"%64",
	"%65",
	"%66",
	"%67",
	"%68",
	"%69",
	"%6A",
	"%6B",
	"%6C",
	"%6D",
	"%6E",
	"%6F",
	"%70",
	"%71",
	"%72",
	"%73",
	"%74",
	"%75",
	"%76",
	"%77",
	"%78",
	"%79",
	"%7A",
	"%7B",
	"%7C",
	"%7D",
	"%7E",
	"%A2",
	"%A3",
	"%A5",
	"%A6",
	"%A7",
	"%AB",
	"%AC",
	"%AD",
	"%B0",
	"%B1",
	"%B2",
	"%B4",
	"%B5",
	"%BB",
	"%BC",
	"%BD",
	"%BF",
	"%C0",
	"%C1",
	"%C2",
	"%C3",
	"%C4",
	"%C5",
	"%C6",
	"%C7",
	"%C8",
	"%C9",
	"%CA",
	"%CB",
	"%CC",
	"%CD",
	"%CE",
	"%CF",
	"%D0",
	"%D1",
	"%D2",
	"%D3",
	"%D4",
	"%D5",
	"%D6",
	"%D8",
	"%D9",
	"%DA",
	"%DB",
	"%DC",
	"%DD",
	"%DE",
	"%DF",
	"%E0",
	"%E1",
	"%E2",
	"%E3",
	"%E4",
	"%E5",
	"%E6",
	"%E7",
	"%E8",
	"%E9",
	"%EA",
	"%EB",
	"%EC",
	"%ED",
	"%EE",
	"%EF",
	"%F0",
	"%F1",
	"%F2",
	"%F3",
	"%F4",
	"%F5",
	"%F6",
	"%F7",
	"%F8",
	"%F9",
	"%FA",
	"%FB",
	"%FC",
	"%FD",
	"%FE",
	"%FF"
];

// Alphanumeric Characters
var alpha_char = 
[
	'backspace',
	'\t',
	'linefeed',
	'creturn',
	" ",
	"!",
	'"',
	"#",
	"$",
	"%",
	"&",
	"'",
	"(",
	")",
	"*",
	"+",
	",",
	"-",
	".",
	"/",
	"0",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	":",
	";",
	"<",
	"=",
	">",
	"?",
	"@",
	"A",
	"B",
	"C",
	"D",
	"E",
	"F",
	"G",
	"H",
	"I",
	"J",
	"K",
	"L",
	"M",
	"N",
	"O",
	"P",
	"Q",
	"R",
	"S",
	"T",
	"U",
	"V",
	"W",
	"X",
	"Y",
	"Z",
	"[",
	'\\',
	"]",
	"^",
	"_",
	"`",
	"a",
	"b",
	"c",
	"d",
	"e",
	"f",
	"g",
	"h",
	"i",
	"j",
	"k",
	"l",
	"m",
	"n",
	"o",
	"p",
	"q",
	"r",
	"s",
	"t",
	"u",
	"v",
	"w",
	"x",
	"y",
	"z",
	"{",
	"|",
	"}",
	"~",
	"¢",
	"£",
	"¥",
	"|",
	"§",
	"«",
	"¬",
	"¯",
	"º",
	"±",
	"ª",
	",",
	"µ",
	"»",
	"¼",
	"½",
	"¿",
	"À",
	"Á",
	"Â",
	"Ã",
	"Ä",
	"Å",
	"Æ",
	"Ç",
	"È",
	"É",
	"Ê",
	"Ë",
	"Ì",
	"Í",
	"Î",
	"Ï",
	"Ð",
	"Ñ",
	"Ò",
	"Ó",
	"Ô",
	"Õ",
	"Ö",
	"Ø",
	"Ù",
	"Ú",
	"Û",
	"Ü",
	"Ý",
	"Þ",
	"ß",
	"à",
	"á",
	"â",
	"ã",
	"ä",
	"å",
	"æ",
	"ç",
	"è",
	"é",
	"ê",
	"ë",
	"ì",
	"í",
	"î",
	"ï",
	"ð",
	"ñ",
	"ò",
	"ó",
	"ô",
	"õ",
	"ö",
	"÷",
	"ø",
	"ù",
	"ú",
	"û",
	"ü",
	"ý",
	"þ",
	"ÿ"
];

// Dictionary
var converstion = 
[
	{key : "%08", value : "backspace"},
	{key : "%09", value : "	"},
	{key : "%0A", value : "linefeed"},
	{key : "%0D", value : "creturn"},
	{key : "%20", value : " "},
	{key : "%21", value : "!"},
	{key : "%22", value : '"'},
	{key : "%23", value : "#"},
	{key : "%24", value : "$"},
	{key : "%25", value : "%"},
	{key : "%26", value : "&"},
	{key : "%27", value : "'"},
	{key : "%28", value : "("},
	{key : "%29", value : ")"},
	{key : "%2A", value : "*"},
	{key : "%2B", value : "+"},
	{key : "%2C", value : ","},
	{key : "%2D", value : "-"},
	{key : "%2E", value : "."},
	{key : "%2F", value : "/"},
	{key : "%30", value : "0"},
	{key : "%31", value : "1"},
	{key : "%32", value : "2"},
	{key : "%33", value : "3"},
	{key : "%34", value : "4"},
	{key : "%35", value : "5"},
	{key : "%36", value : "6"},
	{key : "%37", value : "7"},
	{key : "%38", value : "8"},
	{key : "%39", value : "9"},
	{key : "%3A", value : ":"},
	{key : "%3B", value : ";"},
	{key : "%3C", value : "<"},
	{key : "%3D", value : "="},
	{key : "%3E", value : ">"},
	{key : "%3F", value : "?"},
	{key : "%40", value : "@"},
	{key : "%41", value : "A"},
	{key : "%42", value : "B"},
	{key : "%43", value : "C"},
	{key : "%44", value : "D"},
	{key : "%45", value : "E"},
	{key : "%46", value : "F"},
	{key : "%47", value : "G"},
	{key : "%48", value : "H"},
	{key : "%49", value : "I"},
	{key : "%4A", value : "J"},
	{key : "%4B", value : "K"},
	{key : "%4C", value : "L"},
	{key : "%4D", value : "M"},
	{key : "%4E", value : "N"},
	{key : "%4F", value : "O"},
	{key : "%50", value : "P"},
	{key : "%51", value : "Q"},
	{key : "%52", value : "R"},
	{key : "%53", value : "S"},
	{key : "%54", value : "T"},
	{key : "%55", value : "U"},
	{key : "%56", value : "V"},
	{key : "%57", value : "W"},
	{key : "%58", value : "X"},
	{key : "%59", value : "Y"},
	{key : "%5A", value : "Z"},
	{key : "%5B", value : "["},
	{key : "%5C", value : "\\"},
	{key : "%5D", value : "]"},
	{key : "%5E", value : "^"},
	{key : "%5F", value : "_"},
	{key : "%60", value : "`"},
	{key : "%61", value : "a"},
	{key : "%62", value : "b"},
	{key : "%63", value : "c"},
	{key : "%64", value : "d"},
	{key : "%65", value : "e"},
	{key : "%66", value : "f"},
	{key : "%67", value : "g"},
	{key : "%68", value : "h"},
	{key : "%69", value : "i"},
	{key : "%6A", value : "j"},
	{key : "%6B", value : "k"},
	{key : "%6C", value : "l"},
	{key : "%6D", value : "m"},
	{key : "%6E", value : "n"},
	{key : "%6F", value : "o"},
	{key : "%70", value : "p"},
	{key : "%71", value : "q"},
	{key : "%72", value : "r"},
	{key : "%73", value : "s"},
	{key : "%74", value : "t"},
	{key : "%75", value : "u"},
	{key : "%76", value : "v"},
	{key : "%77", value : "w"},
	{key : "%78", value : "x"},
	{key : "%79", value : "y"},
	{key : "%7A", value : "z"},
	{key : "%7B", value : "{"},
	{key : "%7C", value : "|"},
	{key : "%7D", value : "}"},
	{key : "%7E", value : "~"},
	{key : "%A2", value : "¢"},
	{key : "%A3", value : "£"},
	{key : "%A5", value : "¥"},
	{key : "%A6", value : "|"},
	{key : "%A7", value : "§"},
	{key : "%AB", value : "«"},
	{key : "%AC", value : "¬"},
	{key : "%AD", value : "¯"},
	{key : "%B0", value : "º"},
	{key : "%B1", value : "±"},
	{key : "%B2", value : "ª"},
	{key : "%B4", value : ","},
	{key : "%B5", value : "µ"},
	{key : "%BB", value : "»"},
	{key : "%BC", value : "¼"},
	{key : "%BD", value : "½"},
	{key : "%BF", value : "¿"},
	{key : "%C0", value : "À"},
	{key : "%C1", value : "Á"},
	{key : "%C2", value : "Â"},
	{key : "%C3", value : "Ã"},
	{key : "%C4", value : "Ä"},
	{key : "%C5", value : "Å"},
	{key : "%C6", value : "Æ"},
	{key : "%C7", value : "Ç"},
	{key : "%C8", value : "È"},
	{key : "%C9", value : "É"},
	{key : "%CA", value : "Ê"},
	{key : "%CB", value : "Ë"},
	{key : "%CC", value : "Ì"},
	{key : "%CD", value : "Í"},
	{key : "%CE", value : "Î"},
	{key : "%CF", value : "Ï"},
	{key : "%D0", value : "Ð"},
	{key : "%D1", value : "Ñ"},
	{key : "%D2", value : "Ò"},
	{key : "%D3", value : "Ó"},
	{key : "%D4", value : "Ô"},
	{key : "%D5", value : "Õ"},
	{key : "%D6", value : "Ö"},
	{key : "%D8", value : "Ø"},
	{key : "%D9", value : "Ù"},
	{key : "%DA", value : "Ú"},
	{key : "%DB", value : "Û"},
	{key : "%DC", value : "Ü"},
	{key : "%DD", value : "Ý"},
	{key : "%DE", value : "Þ"},
	{key : "%DF", value : "ß"},
	{key : "%E0", value : "à"},
	{key : "%E1", value : "á"},
	{key : "%E2", value : "â"},
	{key : "%E3", value : "ã"},
	{key : "%E4", value : "ä"},
	{key : "%E5", value : "å"},
	{key : "%E6", value : "æ"},
	{key : "%E7", value : "ç"},
	{key : "%E8", value : "è"},
	{key : "%E9", value : "é"},
	{key : "%EA", value : "ê"},
	{key : "%EB", value : "ë"},
	{key : "%EC", value : "ì"},
	{key : "%ED", value : "í"},
	{key : "%EE", value : "î"},
	{key : "%EF", value : "ï"},
	{key : "%F0", value : "ð"},
	{key : "%F1", value : "ñ"},
	{key : "%F2", value : "ò"},
	{key : "%F3", value : "ó"},
	{key : "%F4", value : "ô"},
	{key : "%F5", value : "õ"},
	{key : "%F6", value : "ö"},
	{key : "%F7", value : "÷"},
	{key : "%F8", value : "ø"},
	{key : "%F9", value : "ù"},
	{key : "%FA", value : "ú"},
	{key : "%FB", value : "û"},
	{key : "%FC", value : "ü"},
	{key : "%FD", value : "ý"},
	{key : "%FE", value : "þ"},
	{key : "%FF", value : "ÿ"}
];

var file_name = process.argv[2]; // Get filename from argument

// Stop program if file does not exist
if (!fs.existsSync(file_name)) 
{
	console.log("File not found!");
	process.exit(); // Kill program
}

var data = fs.readFileSync(file_name); // Read file
var sentence = data.toString(); // Convert file contents to string format
var new_sentence = "";
var new_file_name =  "decoded_" + file_name;

// Convert to Encoded characters to Alphanumeric characters
new_sentence = sentence.replace(new RegExp(codes.join('|'), 'ig'), function (c) 
{
	return alpha_char[codes.indexOf(c)];
});

// Write decoded text to file
fs.writeFile(new_file_name, new_sentence, function(err) 
{
	if (err) 
	{
		return console.error(err);
	}
});

console.log("Process Complete!");

/*
	Source : 
	http://www.degraeve.com/reference/urlencoding.php
	https://fiddle.jshell.net/lnfnunes/x78tye8a/
*/